### ISSUE TITLE
No release notes when force pushing to branch

### ISSUE THREAD

**Issue by greenkiwi** [guilhermetod/semantic-release-notes-preview#1]
We are experiencing strange behavior when we force push branches in a PR.

We see that there will be "no new release" generated, even when it's pretty clear that there is a commit with a change that would generate the change.

When I first committed the changes, it generated release notes.  Then when I rebased and force pushed changes up, it did not.

Here is the commit message:
![image](https://user-images.githubusercontent.com/54169/184567841-78175e3f-5b28-40d3-9d58-4ed98322f013.png)

Here's the output:
![image](https://user-images.githubusercontent.com/54169/184567756-cdce49a5-c21a-4895-9361-d5f6ea3f0ca8.png)

And we are setting the fetch depth to `0`
```
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm install
      - name: Generate release notes
        id: release-notes-preview
        uses: guilhermetod/semantic-release-notes-preview@v1.0.0
```
